[[constraint]]
  version = "v1.11.5"
  name = "k8s.io/kubernetes"

[[constraint]]
  version = "kubernetes-1.11.5"
  name = "k8s.io/apiserver"

[[constraint]]
  version = "kubernetes-1.11.5"
  name = "k8s.io/api"

[[constraint]]
  version = "kubernetes-1.11.5"
  name = "k8s.io/apimachinery"

[[override]]
  version = "kubernetes-1.11.5"
  name = "k8s.io/apiextensions-apiserver"

# Fix vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[prune]
  go-tests = true
  unused-packages = true
