apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: linkedcare-controller-manager
  name: linkedcare-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkedcare-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: linkedcare-controller-manager
    spec:
      containers:
      - args:
        - /usr/local/bin/cloud-controller-manager
        - --cloud-provider=alicloud
        - --configure-cloud-routes=false
        env:
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access-key-id
              name: cloud-config
        - name: ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: access-key-secret
              name: cloud-config
        - name: REGION_ID
          valueFrom:
            secretKeyRef:
              key: region-id
              name: cloud-config
        image: registry.cn-hangzhou.aliyuncs.com/linkedcare/linkedcare-cloud-controller-manager:latest
        imagePullPolicy: Always
        name: cloud-controller-manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
      nodeSelector:
        node-role.kubernetes.io/master: ""
      imagePullSecrets:
      - name: registry-secret
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kubernetes-dashboard-admin
      serviceAccountName: kubernetes-dashboard-admin
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
